-- DS-CANDYSHOP ITEMS
-- Add these items to your rsg-core/shared/items.lua file

-- CANDY SHOP INGREDIENTS
consumable_candy_bag                                 = { name = 'consumable_candy_bag',                   label = 'Candy Bag',                         weight = 25,  type = 'item', image = 'consumable_candy_bag.png',                                                   unique = false, useable = false, shouldClose = true, description = 'Small bag for storing candies' },
lemon                                                = { name = 'lemon',                                  label = 'Lemon',                             weight = 100, type = 'item', image = 'lemon.png',                                                               unique = false, useable = true, shouldClose = true, description = 'Fresh lemon for flavoring' },
blueberry                                            = { name = 'blueberry',                              label = 'Blueberry',                         weight = 50,  type = 'item', image = 'blueberry.png',                                                             unique = false, useable = true, shouldClose = true, description = 'Fresh blueberries for candy making' },
grapes                                               = { name = 'grapes',                                 label = 'Grapes',                            weight = 100, type = 'item', image = 'grapes.png',                                                              unique = false, useable = true, shouldClose = true, description = 'Fresh grapes for flavoring' },
salt                                                 = { name = 'salt',                                   label = 'Salt',                              weight = 100, type = 'item', image = 'salt.png',                                                                unique = false, useable = false, shouldClose = true, description = 'Salt for enhancing flavors' },
lumber_sticks                                        = { name = 'lumber_sticks',                          label = 'Wooden Sticks',                     weight = 50,  type = 'item', image = 'lumber_sticks.png',                                                       unique = false, useable = false, shouldClose = true, description = 'Small wooden sticks for candy apples' },

-- CANDY SHOP BLUEPRINTS
bpo_hard_candy                                       = { name = 'bpo_hard_candy',                         label = 'Hard Candy Blueprint (Original)',   weight = 100, type = 'item', image = 'bpo_hard_candy.png',                                                    unique = false, useable = false, shouldClose = true, description = 'Reusable blueprint for making hard candies' },
bpc_hard_candy                                       = { name = 'bpc_hard_candy',                         label = 'Hard Candy Blueprint (Copy)',       weight = 50,  type = 'item', image = 'bpc_hard_candy.png',                                                    unique = false, useable = false, shouldClose = true, description = 'Single-use blueprint copy for making hard candies' },
bpo_soft_candy                                       = { name = 'bpo_soft_candy',                         label = 'Soft Candy Blueprint (Original)',   weight = 100, type = 'item', image = 'bpo_soft_candy.png',                                                    unique = false, useable = false, shouldClose = true, description = 'Reusable blueprint for making soft candies' },
bpc_soft_candy                                       = { name = 'bpc_soft_candy',                         label = 'Soft Candy Blueprint (Copy)',       weight = 50,  type = 'item', image = 'bpc_soft_candy.png',                                                    unique = false, useable = false, shouldClose = true, description = 'Single-use blueprint copy for making soft candies' },
bpo_wafers                                           = { name = 'bpo_wafers',                             label = 'Wafers Blueprint (Original)',       weight = 100, type = 'item', image = 'bpo_wafers.png',                                                        unique = false, useable = false, shouldClose = true, description = 'Reusable blueprint for making wafers' },
bpc_wafers                                           = { name = 'bpc_wafers',                             label = 'Wafers Blueprint (Copy)',           weight = 50,  type = 'item', image = 'bpc_wafers.png',                                                        unique = false, useable = false, shouldClose = true, description = 'Single-use blueprint copy for making wafers' },
bpo_chocolate                                        = { name = 'bpo_chocolate',                          label = 'Chocolate Blueprint (Original)',    weight = 100, type = 'item', image = 'bpo_chocolate.png',                                                     unique = false, useable = false, shouldClose = true, description = 'Reusable blueprint for making chocolate candies' },
bpc_chocolate                                        = { name = 'bpc_chocolate',                          label = 'Chocolate Blueprint (Copy)',        weight = 50,  type = 'item', image = 'bpc_chocolate.png',                                                     unique = false, useable = false, shouldClose = true, description = 'Single-use blueprint copy for making chocolate candies' },
bpo_specialty                                        = { name = 'bpo_specialty',                          label = 'Specialty Treats Blueprint (Original)', weight = 100, type = 'item', image = 'bpo_specialty.png',                                               unique = false, useable = false, shouldClose = true, description = 'Reusable blueprint for making specialty treats' },
bpc_specialty                                        = { name = 'bpc_specialty',                          label = 'Specialty Treats Blueprint (Copy)', weight = 50,  type = 'item', image = 'bpc_specialty.png',                                                     unique = false, useable = false, shouldClose = true, description = 'Single-use blueprint copy for making specialty treats' },

-- FINISHED CANDY PRODUCTS
consumable_candy_hard_milk                           = { name = 'consumable_candy_hard_milk',             label = 'Hard Milk Candy',                   weight = 75,  type = 'item', image = 'consumable_candy_hard_milk.png',                                             unique = false, useable = true, shouldClose = true, description = 'Sweet hard milk candy' },
consumable_peppermint                                = { name = 'consumable_peppermint',                  label = 'Peppermint Candy',                  weight = 50,  type = 'item', image = 'consumable_peppermint.png',                                                unique = false, useable = true, shouldClose = true, description = 'Refreshing peppermint hard candy' },
consumable_lemon_drops                               = { name = 'consumable_lemon_drops',                 label = 'Lemon Drops',                       weight = 50,  type = 'item', image = 'consumable_lemon_drops.png',                                               unique = false, useable = true, shouldClose = true, description = 'Tangy lemon drop candies' },
consumable_candycanes                                = { name = 'consumable_candycanes',                  label = 'Candy Canes',                       weight = 75,  type = 'item', image = 'consumable_candycanes.png',                                                unique = false, useable = true, shouldClose = true, description = 'Festive striped candy canes' },
consumable_candy_salt_water_taffy_blueberry          = { name = 'consumable_candy_salt_water_taffy_blueberry', label = 'Blueberry Taffy',               weight = 100, type = 'item', image = 'consumable_candy_salt_water_taffy_blueberry.png',                         unique = false, useable = true, shouldClose = true, description = 'Chewy blueberry salt water taffy' },
consumable_candy_salt_water_taffy_grape              = { name = 'consumable_candy_salt_water_taffy_grape', label = 'Grape Taffy',                       weight = 100, type = 'item', image = 'consumable_candy_salt_water_taffy_grape.png',                             unique = false, useable = true, shouldClose = true, description = 'Sweet grape salt water taffy' },
consumable_candy_salt_water_taffy_strawberry         = { name = 'consumable_candy_salt_water_taffy_strawberry', label = 'Strawberry Taffy',             weight = 100, type = 'item', image = 'consumable_candy_salt_water_taffy_strawberry.png',                       unique = false, useable = true, shouldClose = true, description = 'Delicious strawberry salt water taffy' },
consumable_candy_salt_water_taffy_pear               = { name = 'consumable_candy_salt_water_taffy_pear', label = 'Green Apple Taffy',                 weight = 100, type = 'item', image = 'consumable_candy_salt_water_taffy_pear.png',                               unique = false, useable = true, shouldClose = true, description = 'Tart green apple salt water taffy' },
consumable_sugar_wafer_chocolate                     = { name = 'consumable_sugar_wafer_chocolate',       label = 'Chocolate Sugar Wafer',             weight = 125, type = 'item', image = 'consumable_sugar_wafer_chocolate.png',                                     unique = false, useable = true, shouldClose = true, description = 'Crispy chocolate sugar wafer' },
consumable_sugar_wafer_strawberry                    = { name = 'consumable_sugar_wafer_strawberry',      label = 'Strawberry Sugar Wafer',            weight = 125, type = 'item', image = 'consumable_sugar_wafer_strawberry.png',                                    unique = false, useable = true, shouldClose = true, description = 'Sweet strawberry sugar wafer' },
consumable_sugar_wafer_vanilla                       = { name = 'consumable_sugar_wafer_vanilla',         label = 'Vanilla Sugar Wafer',               weight = 125, type = 'item', image = 'consumable_sugar_wafer_vanilla.png',                                       unique = false, useable = true, shouldClose = true, description = 'Classic vanilla sugar wafer' },
consumable_honeycomb_candy                           = { name = 'consumable_honeycomb_candy',             label = 'Chocolate Bar',                     weight = 150, type = 'item', image = 'consumable_honeycomb_candy.png',                                           unique = false, useable = true, shouldClose = true, description = 'Rich chocolate bar with honeycomb' },
consumable_apple_candy                               = { name = 'consumable_apple_candy',                 label = 'Candy Apple',                       weight = 200, type = 'item', image = 'consumable_apple_candy.png',                                               unique = false, useable = true, shouldClose = true, description = 'Classic candy apple on a stick' },

-- CANDY SHOP LICENSE (if Config.LicenseRequired = true)
candyshoplicence                                     = { name = 'candyshoplicence',                       label = 'Candy Shop License',                weight = 50,  type = 'item', image = 'candyshoplicence.png',                                                    unique = false, useable = false, shouldClose = true, description = 'Official license to operate a candy shop' },