valcandyshop = {
    label = 'Valentine Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
blacandyshop = {
    label = 'Blackwater Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
rhocandyshop = {
    label = 'Rhodes Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
doycandyshop = {
    label = 'Saint Denis Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
strcandyshop = {
    label = 'Strawberry Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
oldcandyshop = {
    label = 'Old Light Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
armcandyshop = {
    label = 'Armadillo Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
tumcandyshop = {
    label = 'Tumbleweed Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},
guarcandyshop = {
    label = 'Guarma Candy Shop',
    type = 'candyshop',
    defaultDuty = false,
    offDutyPay = false,
    grades = {
        ['0'] = { name = 'Apprentice', payment = 10 },
        ['1'] = { name = 'Candy Maker', payment = 15 },
        ['2'] = { name = 'Shop Owner', isboss = true, payment = 25 },
    },
},